# Generated by Django 4.2.14 on 2024-09-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_subscription_cart_product_cart_quantity_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
